# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Socialtext-Resting
version:      0.02
version_from: lib/Socialtext/Resting.pm
installdirs:  site
requires:
    App::Options:                  0
    Class::Field:                  0
    HTTP::Request:                 0
    LWP::UserAgent:                0
    Pod::Usage:                    0
    Readonly:                      0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
