--- #YAML:1.0
name:                Socialtext-Resting
version:             0.24
abstract:            Simple tool to use Socialtext RESTful API
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    App::Options:                  0
    Class::Field:                  0
    HTTP::Request:                 0
    IPC::Run:                      0
    JSON:                          0
    LWP::UserAgent:                0
    Pod::Usage:                    0
    Readonly:                      0
    Test::Mock::LWP:               0.05
    URI::Escape:                   1.31
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Chris Dent <chris.dent@socialtext.com>, Kirsten Jones <kirsten.jones@socialtext.com>
